@Outcome @Regression
Feature: Outcomes Tests

  @Census27Test
  Scenario Outline: As a Gateway I can receive an outcome from TM and create Census Events
    Given an "<SurveyType>" "<BusinessFunction>" outcome message
    And its Primary Outcome is "<Primary Outcome>"
    And its secondary Outcome "<Secondary Outcome>"
    And its Outcome code is "<Outcome Code>"
    And the message includes a Linked QID "<HasLinkedQID>"
    And the message includes a Fulfillment Request "<HasFulfilmentRequest>"
    When Gateway receives the outcome
    Then It will run the following processors "<Operation List>"
    And create the following messages to RM "<RmMessages>"
    And each message has the correct values
    And it will create the following messages "<JsMessages>" to JobService

#    @SPG
#    Examples: SPG
#      | SurveyType | BusinessFunction      | Primary Outcome     | Secondary Outcome                       | Outcome Code | HasLinkedQID | HasFulfilmentRequest | Operation List                                                                 | RmMessages                                                  | JsMessages |
#      | SPG        | Not Valid Address     | Not Valid           | Visit - Unoccupied Site                 | 6-30-03      | F            | F                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID                                           | CANCEL     |
#      | SPG        | Not Valid Address     | Not Valid           | Visit - Unoccupied Site                 | 6-30-03      | T            | F                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                      | CANCEL     |
#      | SPG        | Not Valid Address     | Not Valid           | Visit - Unoccupied Site                 | 6-30-03      | F            | T                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                      | CANCEL     |
#      | SPG        | Not Valid Address     | Not Valid           | Visit - Unoccupied Site                 | 6-30-03      | T            | T                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED | CANCEL     |
#
#      | SPG        | Hard Refusal          | Contact Made        | Phone - Hard Refusal                    | 6-20-04      | F            | F                    |                                                                                |                                                             |            |
#      | SPG        | Hard Refusal          | Contact Made        | Phone - Hard Refusal                    | 6-20-04      | T            | F                    |                                                                                |                                                             |            |
#      | SPG        | Hard Refusal          | Contact Made        | Phone - Hard Refusal                    | 6-20-04      | F            | T                    |                                                                                |                                                             |            |
#      | SPG        | Hard Refusal          | Contact Made        | Phone - Hard Refusal                    | 6-20-04      | T            | T                    |                                                                                |                                                             |            |
#
#      | SPG        | Extraordinary Refusal | Contact Made        | Phone - Extraordinary Refusal           | 6-20-05      | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                            | CANCEL     |
#      | SPG        | Extraordinary Refusal | Contact Made        | Phone - Extraordinary Refusal           | 6-20-05      | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                       | CANCEL     |
#      | SPG        | Extraordinary Refusal | Contact Made        | Phone - Extraordinary Refusal           | 6-20-05      | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                       | CANCEL     |
#      | SPG        | Extraordinary Refusal | Contact Made        | Phone - Extraordinary Refusal           | 6-20-05      | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  | CANCEL     |
#
#      | SPG        | Cancel Feedback       | Contact Made        | HICL or Paper H Questionnaire delivered | 22-20-05     | F            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                |                                                             | CANCEL     |
#      | SPG        | Cancel Feedback       | Contact Made        | HICL or Paper H Questionnaire delivered | 22-20-05     | T            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | QUESTIONNAIRE_LINKED                                        | CANCEL     |
#      | SPG        | Cancel Feedback       | Contact Made        | HICL or Paper H Questionnaire delivered | 22-20-05     | F            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED                                        | CANCEL     |
#      | SPG        | Cancel Feedback       | Contact Made        | HICL or Paper H Questionnaire delivered | 22-20-05     | T            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                   | CANCEL     |
#
#      | SPG        | Delivered Feedback    | Contact Made        | HUAC required by text                   | 7-20-04      | F            | F                    | DELIVERED_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                             |                                                             | UPDATE     |
#      | SPG        | Delivered Feedback    | Contact Made        | HUAC required by text                   | 7-20-04      | T            | F                    | DELIVERED_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                             | QUESTIONNAIRE_LINKED                                        | UPDATE     |
#      | SPG        | Delivered Feedback    | Contact Made        | HUAC required by text                   | 7-20-04      | F            | T                    | DELIVERED_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                             | FULFILMENT_REQUESTED                                        | UPDATE     |
#      | SPG        | Delivered Feedback    | Contact Made        | HUAC required by text                   | 7-20-04      | T            | T                    | DELIVERED_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                             | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                   | UPDATE     |
#
#      | SPG        | No Action             | Irrelevant          | Irrelevant                              | 6-20-02      | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                             |            |
#      | SPG        | No Action             | Irrelevant          | Irrelevant                              | 6-20-02      | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                        |            |
#      | SPG        | No Action             | Irrelevant          | Irrelevant                              | 6-20-02      | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                        |            |
#      | SPG        | No Action             | Irrelevant          | Irrelevant                              | 6-20-02      | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                   |            |
#
    @CE
    Examples: CE
      | SurveyType | BusinessFunction      | Primary Outcome     | Secondary Outcome                   | Outcome Code | HasLinkedQID | HasFulfilmentRequest | Operation List                                                                 | RmMessages                                                   | JsMessages |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 22-30-01     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 22-30-01     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 22-30-01     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 22-30-01     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 22-30-02     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 22-30-02     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 22-30-02     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 22-30-02     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 22-30-03     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 22-30-03     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 22-30-03     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 22-30-03     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 22-30-04     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 22-30-04     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 22-30-04     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 22-30-04     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied site             | 22-30-05     | F            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                |                                                              | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied site             | 22-30-05     | T            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | QUESTIONNAIRE_LINKED                                         | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied site             | 22-30-05     | F            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED                                         | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied site             | 22-30-05     | T            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    | CANCEL     |

      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 22-20-04     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                             | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 22-20-04     | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 22-20-04     | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 22-20-04     | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED   | CANCEL     |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 22-20-15     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 22-20-15     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 22-20-15     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 22-20-15     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 22-20-16     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 22-20-16     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 22-20-16     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 22-20-16     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 22-20-17     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 22-20-17     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 22-20-17     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 22-20-17     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 22-20-18     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 22-20-18     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 22-20-18     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 22-20-18     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 22-20-11     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                             | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 22-20-11     | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 22-20-11     | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 22-20-11     | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED   | CANCEL     |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 22-20-19     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 22-20-19     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 22-20-19     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 22-20-19     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 22-20-20     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 22-20-20     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 22-20-20     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 22-20-20     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 22-20-21     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 22-20-21     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 22-20-21     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 22-20-21     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |

      | CE         | Not Valid Address     | Not a valid CE Est  | Visit - Not a valid CE Est          | 22-10-18     | F            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID                                            |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Visit - Not a valid CE Est          | 22-10-18     | T            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Visit - Not a valid CE Est          | 22-10-18     | F            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Visit - Not a valid CE Est          | 22-10-18     | T            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Phone - Not a valid CE Est          | 22-10-19     | F            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID                                            |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Phone - Not a valid CE Est          | 22-10-19     | T            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Phone - Not a valid CE Est          | 22-10-19     | F            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       |            |
      | CE         | Not Valid Address     | Not a valid CE Est  | Phone - Not a valid CE Est          | 22-10-19     | T            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  |            |

      | CE         | Update Resident Count | Contact made        | Will or have completed              | 25-20-01     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact made        | Will or have completed              | 25-20-01     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact made        | Will or have completed              | 25-20-01     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact made        | Will or have completed              | 25-20-01     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact made        | Visit another time                  | 25-20-03     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact made        | Visit another time                  | 25-20-03     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact made        | Visit another time                  | 25-20-03     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact made        | Visit another time                  | 25-20-03     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Extraordinary Refusal | Contact made        | Extraordinary Refusal               | 25-20-05     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                             | CANCEL     |
      | CE         | Extraordinary Refusal | Contact made        | Extraordinary Refusal               | 25-20-05     | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact made        | Extraordinary Refusal               | 25-20-05     | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact made        | Extraordinary Refusal               | 25-20-05     | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED   | CANCEL     |

      | CE         | No Action             | No contact made     | Resident is out                     | 25-30-01     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No contact made     | Resident is out                     | 25-30-01     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No contact made     | Resident is out                     | 25-30-01     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No contact made     | Resident is out                     | 25-30-01     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No contact made     | Inaccessible or no access           | 25-30-02     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No contact made     | Inaccessible or no access           | 25-30-02     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No contact made     | Inaccessible or no access           | 25-30-02     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No contact made     | Inaccessible or no access           | 25-30-02     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Not Valid Address     | No contact made     | Unit unoccupied                     | 25-30-03     | F            | F                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID                                            | CANCEL     |
      | CE         | Not Valid Address     | No contact made     | Unit unoccupied                     | 25-30-03     | T            | F                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       | CANCEL     |
      | CE         | Not Valid Address     | No contact made     | Unit unoccupied                     | 25-30-03     | F            | T                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       | CANCEL     |
      | CE         | Not Valid Address     | No contact made     | Unit unoccupied                     | 25-30-03     | T            | T                    | ADDRESS_NOT_VALID,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  | CANCEL     |

      | CE         | Not Valid Address     | Not-valid           | Not a valid CE Unit                 | 25-10-12     | F            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID                                            |            |
      | CE         | Not Valid Address     | Not-valid           | Not a valid CE Unit                 | 25-10-12     | T            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       |            |
      | CE         | Not Valid Address     | Not-valid           | Not a valid CE Unit                 | 25-10-12     | F            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       |            |
      | CE         | Not Valid Address     | Not-valid           | Not a valid CE Unit                 | 25-10-12     | T            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  |            |

      | CE         | No Action             | No Contact          | Phone - No answer                   | 21-30-01     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 21-30-01     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 21-30-01     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Phone - No answer                   | 21-30-01     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 21-30-02     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 21-30-02     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 21-30-02     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Phone - PiC not available           | 21-30-02     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 21-30-04     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 21-30-04     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 21-30-04     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Visit - Inaccessible or no access   | 21-30-04     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 21-30-05     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 21-30-05     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 21-30-05     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | No Contact          | Visit - PiC not available           | 21-30-05     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied establishment    | 21-30-06     | F            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                |                                                              | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied establishment    | 21-30-06     | T            | F                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | QUESTIONNAIRE_LINKED                                         | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied establishment    | 21-30-06     | F            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED                                         | CANCEL     |
      | CE         | Cancel Feedback       | No Contact          | Visit - Unoccupied establishment    | 21-30-06     | T            | T                    | CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID                                | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    | CANCEL     |

      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 21-20-01     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 21-20-01     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 21-20-01     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | Contact Made        | Phone - Call back another time      | 21-20-01     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 21-20-04     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                             | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 21-20-04     | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 21-20-04     | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Phone - Extraordinary refusal       | 21-20-04     | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED   | CANCEL     |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 21-20-08     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 21-20-08     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 21-20-08     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Visit another time          | 21-20-08     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 21-20-13     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED                                             | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 21-20-13     | T            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,QUESTIONNAIRE_LINKED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 21-20-13     | F            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED                        | CANCEL     |
      | CE         | Extraordinary Refusal | Contact Made        | Visit - Extraordinary refusal       | 21-20-13     | T            | T                    | EXTRAORDINARY_REFUSAL_RECEIVED,CANCEL_FEEDBACK,FULFILMENT_REQUESTED,LINKED_QID | REFUSAL_RECEIVED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED   | CANCEL     |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 21-20-17     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 21-20-17     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 21-20-17     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up agreed | 21-20-17     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 21-20-18     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 21-20-18     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 21-20-18     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Visit - Access for follow-up denied | 21-20-18     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 21-20-19     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                              |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 21-20-19     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                         |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 21-20-19     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                         |            |
      | CE         | No Action             | Contact Made        | Visit - Census Connect activity     | 21-20-19     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                    |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 21-20-20     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 21-20-20     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 21-20-20     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up agreed | 21-20-20     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 21-20-21     | F            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED                                           |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 21-20-21     | T            | F                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,QUESTIONNAIRE_LINKED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 21-20-21     | F            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED                      |            |
      | CE         | Update Resident Count | Contact Made        | Phone - Access for follow-up denied | 21-20-21     | T            | T                    | UPDATE_RESIDENT_COUNT,FULFILMENT_REQUESTED,LINKED_QID                          | FIELD_CASE_UPDATED,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED |            |

      | CE         | Not Valid Address     | Not a Valid CE Est  | Visit - Not a valid CE Est          | 21-10-17     | F            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID                                            |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Visit - Not a valid CE Est          | 21-10-17     | T            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Visit - Not a valid CE Est          | 21-10-17     | F            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Visit - Not a valid CE Est          | 21-10-17     | T            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Phone - Not a valid CE Est          | 21-10-18     | F            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID                                            |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Phone - Not a valid CE Est          | 21-10-18     | T            | F                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,QUESTIONNAIRE_LINKED                       |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Phone - Not a valid CE Est          | 21-10-18     | F            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED                       |            |
      | CE         | Not Valid Address     | Not a Valid CE Est  | Phone - Not a valid CE Est          | 21-10-18     | T            | T                    | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,LINKED_QID                              | ADDRESS_NOT_VALID,FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED  |            |

    @HH
    Examples: HH
      | SurveyType | BusinessFunction      | Primary Outcome     | Secondary Outcome                       | Outcome Code | HasLinkedQID | HasFulfilmentRequest | Operation List                                                                 | RmMessages                                                    | JsMessages |
      | HH         | No Action             | No contact made     | Householder is out - card left          | 01-01-01     | F            | F                    | NO_ACTION                                                                      |                                                               |            |
      | HH         | No Action             | No contact made     | Householder is out - no card left       | 01-01-02     | F            | F                    | NO_ACTION                                                                      |                                                               |            |
      | HH         | No Action             | No contact made     | Inaccessible or no access               | 01-01-03     | F            | F                    | NO_ACTION                                                                      |                                                               |            |
      | HH         | No Action             | No contact made     | Can't find property                     | 01-01-06     | F            | F                    | NO_ACTION                                                                      |                                                               |            |
      | HH         | No Action             | No contact made     | Vacant property                         | 01-01-07     | F            | F                    | FEEDBACK_LONG_PAUSE                                                            |                                                               | CANCEL     |

      | HH         | No Action             | Contact made        | Will or have completed                  | 01-02-01     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                               |            |
      | HH         | No Action             | Contact made        | Will or have completed                  | 01-02-01     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                          |            |
      | HH         | No Action             | Contact made        | Will or have completed                  | 01-02-01     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                          |            |
      | HH         | No Action             | Contact made        | Will or have completed                  | 01-02-01     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                     |            |
      | HH         | No Action             | Contact made        | Call back another time                  | 01-02-03     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                               |            |
      | HH         | No Action             | Contact made        | Call back another time                  | 01-02-03     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                          |            |
      | HH         | No Action             | Contact made        | Call back another time                  | 01-02-03     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                          |            |
      | HH         | No Action             | Contact made        | Call back another time                  | 01-02-03     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                     |            |
      | HH         | No Action             | Contact made        | Unoccupied property                     | 01-02-04     | F            | F                    | FEEDBACK_LONG_PAUSE                                                            |                                                               | CANCEL     |
      | HH         | No Action             | Contact made        | Split address                           | 01-02-06     | F            | F                    | ADDRESS_NOT_VALID,FEEDBACK_LONG_PAUSE                                          | ADDRESS_NOT_VALID                                             | CANCEL     |
      | HH         | Extraordinary Refusal | Contact made        | Extraordinary refusal                   | 01-02-08     | F            | F                    | EXTRAORDINARY_REFUSAL_RECEIVED,FEEDBACK_LONG_PAUSE                             | REFUSAL_RECEIVED                                              | CANCEL     |
      | HH         | No Action             | Contact made        | Paper HH Questionnaire required by post | 01-02-09     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID,FEEDBACK_LONG_PAUSE                  |                                                               | CANCEL     |
      | HH         | No Action             | Contact made        | Paper HH Questionnaire required by post | 01-02-09     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID,FEEDBACK_LONG_PAUSE                  | QUESTIONNAIRE_LINKED                                          | CANCEL     |
      | HH         | No Action             | Contact made        | Paper HH Questionnaire required by post | 01-02-09     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID,FEEDBACK_LONG_PAUSE                  | FULFILMENT_REQUESTED                                          | CANCEL     |
      | HH         | No Action             | Contact made        | Paper HH Questionnaire required by post | 01-02-09     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID,FEEDBACK_LONG_PAUSE                  | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                     | CANCEL     |
      | HH         | No Action             | Contact made        | HH UAC required by text                 | 01-02-11     | F            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      |                                                               |            |
      | HH         | No Action             | Contact made        | HH UAC required by text                 | 01-02-11     | F            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED                                          |            |
      | HH         | No Action             | Contact made        | HH UAC required by text                 | 01-02-11     | T            | F                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | QUESTIONNAIRE_LINKED                                          |            |
      | HH         | No Action             | Contact made        | HH UAC required by text                 | 01-02-11     | T            | T                    | NO_ACTION,FULFILMENT_REQUESTED,LINKED_QID                                      | FULFILMENT_REQUESTED,QUESTIONNAIRE_LINKED                     |            |
      | HH         | No Action             | Contact made        | Doorstep capture                        | 01-02-14     | F            | F                    | FEEDBACK_LONG_PAUSE                                                            |                                                               | CANCEL     |

      | HH         | Not Valid Address     | Non-valid household | Derelict or demolished                  | 01-03-01     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
      | HH         | Not Valid Address     | Non-valid household | Unaddressable Object                    | 01-03-02     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
      | HH         | Not Valid Address     | Non-valid household | Non-residential                         | 01-03-03     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
      | HH         | Not Valid Address     | Non-valid household | Duplicate                               | 01-03-04     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
      | HH         | Not Valid Address     | Non-valid household | Under construction                      | 01-03-05     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
      | HH         | Not Valid Address     | Non-valid household | Property is a CE                        | 01-03-06     | F            | F                    | ADDRESS_NOT_VALID                                                              | ADDRESS_NOT_VALID                                             |            |
