{
"event":{
"type":"ADDRESS_TYPE_CHANGED",
"source":"FIELDWORK_GATEWAY",
"channel":"FIELD",
"dateTime":"2020-04-17T12:53:11.000+01",
"transactionId":"${transactionId}"
},
"payload":{
"addressTypeChange":{
"newCaseId" : "${newCaseId}",
"collectionCase":{
"id":"${caseId}",
"address":{
"addressType":"HH"
}
}
}
}
}