{
"event":{
"type":"ADDRESS_NOT_VALID",
"source":"FIELDWORK_GATEWAY",
"channel":"FIELD",
"dateTime":"2020-04-17T12:53:11.000+01",
"transactionId":"${transactionId}"
},
"payload":{
"invalidAddress":{
"reason":"${reason}",
"collectionCase":{
"id":"${caseId}"
}
}
}
}