{
"event":{
"type":"FULFILMENT_REQUESTED",
"source":"FIELDWORK_GATEWAY",
"channel":"FIELD",
"dateTime":"2020-04-17T12:53:11.000+01",
"transactionId":"${transactionId}"
},
"payload":{
"fulfilmentRequest":{
"fulfilmentCode":"${fulfilmentCode}",
"caseId":"${caseId}",
"address":{},
"contact":{
"title":null,
"forename":null,
"surname":null,
"telNo":"07777000000"
}
}
}
}
}