{
"event":{
"type":"REFUSAL_RECEIVED",
"source":"FIELDWORK_GATEWAY",
"channel":"FIELD",
"dateTime":"2020-04-17T12:53:11.000+01",
"transactionId":"${transactionId}"
},
"payload":{
"refusal":{
"type":"${reason}",
"agentId":"SH-TWH1-ZA-25",
"collectionCase":{
"id":"${caseId}"
}
}
}
}