service.jobservice.url=http://localhost:8025
service.jobservice.username=user
service.jobservice.password=password
service.outcome.url=http://localhost:8030
service.outcome.HH.endpoint=/hhOutcome/
service.outcome.HHNewUnit.endpoint=/hhOutcome/unitAddress/new
service.outcome.HHStandalone.endpoint=/hhOutcome/standaloneAddress/new
service.outcome.CCSPL.endpoint=/ccsPropertyListingOutcome
service.outcome.CCSInt.endpoint=/ccsInterviewOutcome/
service.outcome.SPG.endpoint=/spgOutcome/
service.outcome.SPGNewUnit.endpoint=/spgOutcome/unitAddress/new
service.outcome.SPGStandalone.endpoint=/spgOutcome/standaloneAddress/new
service.outcome.CE.endpoint=/ceOutcome/
service.outcome.CENewUnit.endpoint=/ceOutcome/unitAddress/new
service.outcome.CEStandalone.endpoint=/ceOutcome/standaloneAddress/new
service.outcome.NC.endpoint=/ncOutcome/
service.outcome.username=user
service.outcome.password=password
service.rmadmpter.url=http://localhost:8010
service.rmadmpter.rabbitmqcheck.url=http://localhost:8010/rabbitHealth
service.rmadmpter.username=
service.rmadmpter.password=
service.tm.url=http://localhost:8000
service.tm.username=
service.tm.password=
service.mocktm.url=http://localhost:8000
service.rabbit.url=localhost
service.rabbit.port=5672
service.rabbit.virtualhost=/
service.rabbit.username=guest
service.rabbit.password=guest
service.ccscsv.url=http://localhost:8060/ingestCCSCsvFile
service.cecsv.url=http://localhost:8060/ingestCeCsvFile
service.addresscheckcsv.url=http://localhost:8060/ingestAddressCheckCsvFile
service.addressfileload.url=http://localhost:8060/ingestAddressLookupCsvFile
service.csvservice.username=user
service.csvservice.password=password
service.csvservice.gcpBucket.directory=gs://csv-bucket-test/
#service.csvservice.gcpBucket.directory=file://${home}/acceptance/data/
outcomeservice.reasonCodeLookup.path: classpath:/reasonCodeLookup.txt

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

spring.datasource.url: jdbc:postgresql://localhost/postgres?currentSchema=fwmtg
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.schema: classpath:/schema.sql
spring.datasource.continue-on-error: false
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.datasource.initialization-mode: always
